export const FECTH_ROOMS_HOME         = 'FECTH_ROOMS_HOME';
export const FECTH_ROOMS_HOME_SUCCESS = 'FECTH_ROOMS_HOME_SUCCESS';
export const FECTH_ROOMS_HOME_ERROR   = 'FECTH_ROOMS_HOME_ERROR';

export const FECTH_ROOMS_PAGE        = 'FECTH_ROOMS_PAGE';
export const FECTH_ROOMS_PAGE_SUCCESS = 'FECTH_ROOMS_PAGE_SUCCESS';
export const FECTH_ROOMS_PAGE_ERROR   = 'FECTH_ROOMS_PAGE_ERROR';

export const FECTH_ROOM_DETAIL  = 'FECTH_ROOM_DETAIL';
export const FECTH_ROOM_DETAIL_SUCCESS  = 'FECTH_ROOM_DETAIL_SUCCESS';
export const FECTH_ROOM_DETAIL_ERROR  = 'FECTH_ROOM_DETAIL_ERROR';

export const FECTH_ROOM_ORTHER  = 'FECTH_ROOM_ORTHER';
export const FECTH_ROOM_ORTHER_SUCCESS  = 'FECTH_ROOM_ORTHER_SUCCESS';
export const FECTH_ROOM_ORTHER_ERROR  = 'FECTH_ROOM_ORTHER_ERROR';

export const FECTH_COUNT_ROOMS  = 'FECTH_COUNT_ROOMS';
export const FECTH_COUNT_ROOMS_SUCCESS  = 'FECTH_COUNT_ROOMS_SUCCESS';
export const FECTH_COUNT_ROOMS_ERROR  = 'FECTH_COUNT_ROOMS_ERROR';

export const FECTH_COUNT_BLOGS  = 'FECTH_COUNT_BLOGS';
export const FECTH_COUNT_BLOGS_SUCCESS  = 'FECTH_COUNT_BLOGS_SUCCESS';
export const FECTH_COUNT_BLOGS_ERROR  = 'FECTH_COUNT_BLOGS_ERROR';

export const FECTH_BLOGS_HOME         = 'FECTH_BLOGS_HOME';
export const FECTH_BLOGS_HOME_SUCCESS = 'FECTH_BLOGS_HOME_SUCCESS';
export const FECTH_BLOGS_HOME_ERROR   = 'FECTH_BLOGS_HOME_ERROR';

export const FECTH_BLOG_RECENT  = 'FECTH_BLOG_RECENT';
export const FECTH_BLOG_RECENT_SUCCESS  = 'FECTH_BLOG_RECENT_SUCCESS';
export const FECTH_BLOG_RECENT_ERROR  = 'FECTH_BLOG_RECENT_ERROR';

export const FECTH_BLOGS_PAGE         = 'FECTH_BLOGS_PAGE';
export const FECTH_BLOGS_PAGE_SUCCESS = 'FECTH_BLOGS_PAGE_SUCCESS';
export const FECTH_BLOGS_PAGE_ERROR   = 'FECTH_BLOGS_PAGE_ERROR';

export const FECTH_BLOG_DETAIL  = 'FECTH_BLOG_DETAIL';
export const FECTH_BLOG_DETAIL_SUCCESS  = 'FECTH_BLOG_DETAIL_SUCCESS';
export const FECTH_BLOG_DETAIL_ERROR  = 'FECTH_BLOG_DETAIL_ERROR';

export const FECTH_USERS_HOME   = 'FECTH_USERS_HOME';

export const FECTH_CAROUSEL     = 'FECTH_CAROUSEL';
export const FECTH_CAROUSEL_SUCCESS = 'FECTH_CAROUSEL_SUCCESS';
export const FECTH_CAROUSEL_ERROR = 'FECTH_CAROUSEL_ERROR';

export const FECTH_IMAGE_PANEL  = 'FECTH_IMAGE_PANEL';
export const FECTH_IMAGE_PANEL_SUCCESS  = 'FECTH_IMAGE_PANEL_SUCCESS';
export const FECTH_IMAGE_PANEL_ERROR  = 'FECTH_IMAGE_PANEL_ERROR';

export const SEARCH_ROOM        = 'SEARCH_ROOM';
export const SEARCH_NAME_ROOM        = 'SEARCH_NAME_ROOM';

export const SEARCH_BLOG        = 'SEARCH_BLOG';
export const CHANGE_CURRENT_PAGE_ROOM = 'CHANGE_CURRENT_PAGE_ROOM';
export const CHANGE_CURRENT_PAGE_BLOG = 'CHANGE_CURRENT_PAGE_BLOG';

export const FECTH_CONTACT = 'FECTH_CONTACT';
export const FECTH_CONTACT_SUCCESS = 'FECTH_CONTACT_SUCCESS';
export const FECTH_CONTACT_ERROR = 'FECTH_CONTACT_ERROR';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';


